import { test, expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
async function login(page:Page,account:string){await page.goto('/');await page.getByRole('button',{name:'登录 / 注册',exact:true}).click();await page.getByLabel('手机号 / 邮箱').fill(account);await page.getByLabel('密码',{exact:true}).fill('Demo-Classroom-2026');await page.locator('dialog form').getByRole('button',{name:'登录',exact:true}).click();await expect(page).toHaveURL(/my-courses/);}
test('首页内容、FAQ与桌面布局',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('付费的服务');await expect(page.locator('.plan-price').filter({hasText:'¥5,999'})).toBeVisible();await page.locator('summary').filter({hasText:'90天首单退款承诺适用于哪一档？'}).click();await expect(page.getByText('不以完成行动任务为退款前提。',{exact:false})).toBeVisible();await mkdir('screenshots',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'screenshots/home-desktop.png',fullPage:true});expect(errors).toEqual([]);
});
test('首页移动端无横向溢出、可注册',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'screenshots/home-mobile.png',fullPage:true});await page.getByRole('button',{name:'登录 / 注册',exact:true}).click();await page.getByRole('button',{name:'注册',exact:true}).click();await page.getByLabel('邮箱',{exact:false}).fill(`e2e-${Date.now()}@example.com`);await page.getByLabel('密码',{exact:true}).fill('Demo-Classroom-2026');await page.getByLabel('确认密码').fill('Demo-Classroom-2026');await page.getByRole('button',{name:'注册并登录'}).click();await expect(page.getByRole('heading',{name:'还没有可以学习的课程'})).toBeVisible();
});
test('学员课程权限、播放、跳转、倍速、退出',async({page})=>{
  await login(page,'student@example.com');await expect(page.locator('.course-card')).toHaveCount(3);await page.getByRole('link',{name:'全部课程',exact:true}).click();await expect(page.locator('.course-card')).toHaveCount(5);await page.getByRole('button',{name:'需要 VIP4'}).click();await expect(page.getByRole('dialog')).toContainText('你的当前等级：VIP3');await page.getByRole('button',{name:'知道了'}).click();await page.getByRole('link',{name:'进入课程'}).first().click();await page.getByRole('link',{name:'1.1 演示视频：播放与权限测试'}).click();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(1);await page.locator('video').evaluate(async(v:HTMLVideoElement)=>{await v.play();v.currentTime=2;});await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThanOrEqual(2);await page.getByLabel('播放速度').selectOption('1.5');expect(await page.locator('video').evaluate((v:HTMLVideoElement)=>v.playbackRate)).toBe(1.5);await page.getByRole('link',{name:'下一节'}).click();await expect(page.getByRole('heading',{name:'1.2 演示视频：下一节'})).toBeVisible();await expect(page.getByRole('link',{name:'下一节'})).toHaveCount(0);await page.getByRole('button',{name:'我的',exact:true}).click();await page.getByRole('button',{name:'退出登录'}).click();await expect(page).toHaveURL('/');
});
test('到期学员不可查看视频',async({page})=>{await login(page,'expired@example.com');await expect(page.getByRole('heading',{name:'课程权限已到期'})).toBeVisible();await page.goto('/lessons/demo-lesson-1');await expect(page.getByText('VIP等级不足或已到期')).toBeVisible();});
test('普通学员不能进入后台',async({page})=>{await login(page,'student@example.com');await page.goto('/admin');await expect(page.getByRole('heading',{name:'需要管理员权限'})).toBeVisible();});
test('后台创建、封面、视频队列上传、排序、移动与删除',async({page})=>{
  await login(page,'admin@example.com');await page.getByRole('link',{name:'管理后台',exact:true}).click();await page.getByRole('button',{name:'新建课程',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('E2E 课程');await page.getByLabel('课程简介').fill('真实上传与权限验收');await page.getByLabel('课程封面',{exact:false}).setInputFiles('tests/fixtures/cover.png');await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.file-name button').filter({hasText:'E2E 课程'}).click();await page.getByRole('button',{name:'新建章节',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('E2E 第一章');await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.file-name button').filter({hasText:'E2E 第一章'}).click();await page.locator('.upload-panel input[type=file]').first().setInputFiles([{name:'e2e-a.mp4',mimeType:'video/mp4',buffer:await (await import('node:fs/promises')).readFile('tests/fixtures/sample.mp4')},{name:'e2e-b.mp4',mimeType:'video/mp4',buffer:await (await import('node:fs/promises')).readFile('tests/fixtures/sample.mp4')}]);await expect(page.getByText('上传完成',{exact:true})).toHaveCount(2);await expect(page.locator('.file-row')).toHaveCount(2);
  await page.getByLabel('拖动排序 e2e-a').dragTo(page.locator('.file-row').filter({hasText:'e2e-b'}));await expect(page.locator('.file-name button').first()).toHaveText('e2e-b');await page.reload();await expect(page.locator('.folder-tree')).toBeVisible();await page.locator('.folder-tree button').filter({hasText:'E2E 第一章'}).click();await expect(page.locator('.file-name button').first()).toHaveText('e2e-b');
  await page.screenshot({path:'screenshots/admin-desktop.png',fullPage:true});await page.getByLabel('移动 e2e-a',{exact:true}).click();await page.getByLabel('目标章节').selectOption('demo-chapter-2');await page.getByRole('button',{name:'确认移动'}).click();await expect(page.locator('.file-row')).toHaveCount(1);await page.locator('.folder-tree').getByRole('button',{name:'全部课程'}).click();await page.getByLabel('删除 E2E 课程',{exact:true}).click();await expect(page.getByRole('dialog')).toContainText('1 个章节、1 个小节');await page.getByRole('button',{name:'确认',exact:true}).click();await expect(page.locator('.file-name button').filter({hasText:'E2E 课程'})).toHaveCount(0);
  await page.locator('.folder-tree button').filter({hasText:'第二章 · 项目实践'}).click();await page.getByLabel('删除 e2e-a',{exact:true}).click();await page.getByRole('button',{name:'确认',exact:true}).click();await expect(page.locator('.file-row')).toHaveCount(0);
});
test('后台学员搜索、权限设置与到期日期',async({page})=>{
  await login(page,'admin@example.com');await page.goto('/admin/users');await page.getByLabel('搜索用户').fill('pending@example.com');await page.getByRole('button',{name:'搜索',exact:true}).click();await expect(page.locator('.user-row').filter({hasText:'待开通学员'})).toBeVisible();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('VIP 等级').selectOption('2');await page.getByLabel('有效至（北京时间）').fill('2030-09-17');await page.getByRole('button',{name:'保存权限'}).click();await expect(page.locator('.user-row').filter({hasText:'待开通学员'})).toContainText('VIP2');await expect(page.locator('.user-row').filter({hasText:'待开通学员'})).toContainText('2030-09-17');await page.screenshot({path:'screenshots/users-desktop.png',fullPage:true});await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('VIP 等级').selectOption('');await page.getByRole('button',{name:'保存权限'}).click();await expect(page.locator('.user-row').filter({hasText:'待开通学员'})).toContainText('未开通');
});
test('学员移动端导航和课程列表',async({page})=>{await page.setViewportSize({width:390,height:844});await login(page,'student@example.com');await expect(page.locator('.course-card')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'screenshots/courses-mobile.png',fullPage:true});});
test('上传失败后刷新，重新选择原文件恢复任务',async({page})=>{
  await login(page,'admin@example.com');await page.goto('/admin');await page.locator('.folder-tree button').filter({hasText:'第二章 · 项目实践'}).click();
  await page.route('**/api/v1/admin/uploads/*/local/*',route=>route.fulfill({status:503,body:'network unavailable'}));
  await page.locator('.upload-panel input[type=file]').first().setInputFiles('tests/fixtures/sample.mp4');await expect(page.getByLabel('重试上传',{exact:true})).toBeVisible();
  await page.unroute('**/api/v1/admin/uploads/*/local/*');await page.reload();await expect(page.getByText('可恢复的上传任务',{exact:true})).toBeVisible();await page.getByRole('button',{name:'恢复',exact:true}).click();await page.locator('.upload-panel input[type=file]').nth(1).setInputFiles('tests/fixtures/sample.mp4');await expect(page.getByText('上传完成',{exact:true})).toBeVisible();await page.locator('.folder-tree button').filter({hasText:'第二章 · 项目实践'}).click();await page.getByLabel('删除 sample',{exact:true}).click();await page.getByRole('button',{name:'确认',exact:true}).click();await expect(page.locator('.file-row')).toHaveCount(0);
});
test('上传失败任务可取消，不留下可播放小节',async({page})=>{
  await login(page,'admin@example.com');await page.goto('/admin');await page.locator('.folder-tree button').filter({hasText:'第二章 · 项目实践'}).click();await page.route('**/api/v1/admin/uploads/*/local/*',route=>route.fulfill({status:503,body:'network unavailable'}));await page.locator('.upload-panel input[type=file]').first().setInputFiles('tests/fixtures/sample.mp4');await expect(page.getByLabel('重试上传',{exact:true})).toBeVisible();await page.getByLabel('取消上传',{exact:true}).click();await expect(page.locator('.file-row')).toHaveCount(0);await expect(page.getByText('已取消',{exact:true})).toBeVisible();
});



