import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { BookOpen, Users, Folder, ChevronRight, Plus, FileVideo, GripVertical, Pencil, Trash2, MoveRight, Search, ArrowUpRight, Home as HomeIcon, ImagePlus, Settings } from 'lucide-react';
import { api, type Account, type Chapter, type Course, type Lesson, type TreeCourse, dateLabel, expiryInput, isExpired, vipLabel } from './api';
import { Confirm, Empty, ErrorNote, ErrorState, Loading, Modal } from './ui';
import UploadPanel, { uploadCover } from './upload';
import SystemSettings from './settings';
export default function Admin(){return <div className="admin-layout"><aside className="admin-sidebar"><span className="sidebar-caption">WORKSPACE</span><h2>管理后台</h2><nav><NavLink to="/admin" end><BookOpen size={18}/>课程管理</NavLink><NavLink to="/admin/users"><Users size={18}/>用户管理</NavLink><NavLink to="/admin/settings"><Settings size={18}/>系统设置</NavLink></nav><div className="sidebar-footer"><Link to="/my-courses">返回学员端<ArrowUpRight size={16}/></Link><small>权限由后台配置，报名线下完成。</small></div></aside><main className="admin-main"><Routes><Route index element={<CourseManager/>}/><Route path="users" element={<UserManager/>}/><Route path="settings" element={<SystemSettings/>}/><Route path="*" element={<Empty title="后台页面不存在"/>}/></Routes></main></div>;}
type Scope={kind:'courses'}|{kind:'chapters';courseId:string}|{kind:'lessons';courseId:string;chapterId:string};
type Edit={kind:'courses'|'chapters'|'lessons';id?:string;title:string;description?:string;requiredVip?:number};
type Row=Course|Chapter|Lesson;
function CourseManager(){
  const [tree,setTree]=useState<TreeCourse[]|null>(null),[error,setError]=useState(''),[scope,setScope]=useState<Scope>({kind:'courses'}),[edit,setEdit]=useState<Edit|null>(null),[remove,setRemove]=useState<{kind:Edit['kind'];id:string;title:string;message:string}|null>(null),[move,setMove]=useState<{kind:'chapters'|'lessons';id:string;title:string}|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[files,setFiles]=useState<File[]|null>(null),[over,setOver]=useState(false);
  const drag=useRef<string|null>(null),navigate=useNavigate();
  const load=useCallback(()=>{api<{courses:TreeCourse[]}>('/admin/tree').then(r=>{setTree(r.courses);setError('');}).catch(e=>setError(e.message));},[]);useEffect(load,[load]);
  const course=scope.kind!=='courses'?tree?.find(c=>c.id===scope.courseId):null;
  const chapter=scope.kind==='lessons'?course?.chapters.find(ch=>ch.id===scope.chapterId):null;
  useEffect(()=>{if(tree&&scope.kind!=='courses'&&(!course||(scope.kind==='lessons'&&!chapter)))setScope({kind:'courses'});},[tree,scope,course,chapter]);
  const rows:Row[]=scope.kind==='courses'?tree||[]:scope.kind==='chapters'?course?.chapters||[]:chapter?.lessons||[];
  function startEdit(row?:Row){setActionError('');setEdit({kind:scope.kind,id:row?.id,title:row?.title||'',description:row&&'description'in row?row.description:'',requiredVip:row&&'requiredVip'in row?row.requiredVip:1});}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!edit)return;setBusy(true);setActionError('');const data=Object.fromEntries(new FormData(e.currentTarget));const file=(e.currentTarget.elements.namedItem('cover') as HTMLInputElement|null)?.files?.[0];
    try{let id=edit.id;if(id)await api(`/admin/${edit.kind}/${id}`,'PATCH',{...data,requiredVip:Number(data.requiredVip)});else{const r=await api<{id:string}>(`/admin/${edit.kind}`,'POST',{...data,requiredVip:Number(data.requiredVip),courseId:scope.kind!=='courses'?scope.courseId:undefined});id=r.id;setEdit({...edit,id,title:String(data.title),description:String(data.description||''),requiredVip:Number(data.requiredVip)||1});}if(file)await uploadCover(file,id!);setEdit(null);load();}
    catch(e){setActionError((e as Error).message);load();}
    finally{setBusy(false);}
  }
  function deletion(row:Row){let message='该小节及视频文件将被删除，此操作不可恢复。';if(scope.kind==='courses'){const c=row as TreeCourse;const lessons=c.chapters.reduce((n,ch)=>n+ch.lessons.length,0);message=`将删除课程、${c.chapters.length} 个章节、${lessons} 个小节及关联文件，此操作不可恢复。`;}else if(scope.kind==='chapters')message=`将删除章节及 ${(row as Chapter).lessons.length} 个小节和关联视频，此操作不可恢复。`;setActionError('');setRemove({kind:scope.kind,id:row.id,title:row.title,message});}
  async function deleteRow(){if(!remove)return;setBusy(true);try{await api(`/admin/${remove.kind}/${remove.id}`,'DELETE');setRemove(null);load();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  async function reorder(target:string){const source=drag.current;drag.current=null;if(!source||source===target)return;const ids=rows.map(r=>r.id),from=ids.indexOf(source),to=ids.indexOf(target);if(from<0||to<0)return;ids.splice(from,1);ids.splice(to,0,source);setActionError('');try{await api('/admin/sort','POST',{kind:scope.kind,parentId:scope.kind==='chapters'?scope.courseId:scope.kind==='lessons'?scope.chapterId:undefined,ids});load();}catch(e){setActionError((e as Error).message);}}
  async function doMove(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!move)return;setBusy(true);try{await api('/admin/move','POST',{...move,targetId:new FormData(e.currentTarget).get('target')});setMove(null);load();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  const targetOptions=move?.kind==='chapters'?(tree||[]).filter(c=>c.id!==course?.id).map(c=>({id:c.id,title:c.title})):(tree||[]).flatMap(c=>c.chapters.filter(ch=>ch.id!==chapter?.id).map(ch=>({id:ch.id,title:`${c.title} / ${ch.title}`})));
  return <><div className="admin-page-heading"><div><span className="eyebrow">CONTENT LIBRARY</span><h1>课程管理</h1><p>像整理文件夹一样，组织你的教学内容。</p></div><button className="button compact" onClick={()=>{setActionError('');setEdit({kind:'courses',title:'',description:'',requiredVip:1});}}><Plus size={17}/>新建课程</button></div>
    {error?<ErrorState message={error} retry={load}/>:!tree?<Loading/>:<div className="file-manager"><aside className="folder-tree"><button className={scope.kind==='courses'?'selected':''} onClick={()=>setScope({kind:'courses'})}><HomeIcon size={15}/>全部课程<span>{tree.length}</span></button>{tree.map(c=><div key={c.id}><button className={course?.id===c.id&&scope.kind==='chapters'?'selected':''} onClick={()=>setScope({kind:'chapters',courseId:c.id})}><Folder size={16}/><span>{c.title}</span></button>{c.chapters.map(ch=><button className={`tree-child ${chapter?.id===ch.id?'selected':''}`} key={ch.id} onClick={()=>setScope({kind:'lessons',courseId:c.id,chapterId:ch.id})}><Folder size={14}/><span>{ch.title}</span></button>)}</div>)}</aside><div className={`file-content ${over?'drag-over':''}`} onDragOver={e=>{e.preventDefault();if(Array.from(e.dataTransfer.types).includes('Files'))setOver(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver(false);}} onDrop={e=>{e.preventDefault();setOver(false);if(e.dataTransfer.files.length){if(scope.kind!=='lessons')setActionError('请先进入一个章节，再拖入视频。');else setFiles(Array.from(e.dataTransfer.files));}}}>
      <div className="file-toolbar"><div className="breadcrumb"><button onClick={()=>setScope({kind:'courses'})}>全部课程</button>{course&&<><ChevronRight size={14}/><button onClick={()=>setScope({kind:'chapters',courseId:course.id})}>{course.title}</button></>}{chapter&&<><ChevronRight size={14}/><span>{chapter.title}</span></>}</div>{scope.kind==='chapters'&&<button className="button secondary compact" onClick={()=>startEdit()}><Plus size={16}/>新建章节</button>}</div>
      <div className="file-context"><h2>{chapter?.title||course?.title||'课程库'}</h2><span>{rows.length} 项 · 拖动把手调整顺序</span></div><ErrorNote message={actionError}/>
      <div className="file-list"><div className="file-list-header"><span>名称</span><span>内容 / 权限</span><span>操作</span></div>{!rows.length?<Empty title={scope.kind==='courses'?'创建你的第一门课程':scope.kind==='chapters'?'添加一个章节':'这个章节还没有视频'}><p className="muted">{scope.kind==='lessons'?'在下方选择或拖入视频文件。':'点击新建按钮开始组织内容。'}</p></Empty>:rows.map(row=><div className="file-row" key={row.id} onDragOver={e=>{if(drag.current){e.preventDefault();e.stopPropagation();}}} onDrop={e=>{if(drag.current){e.preventDefault();e.stopPropagation();reorder(row.id);}}}>
        <span className="file-name"><span className="drag-handle" draggable aria-label={`拖动排序 ${row.title}`} onDragStart={e=>{drag.current=row.id;e.dataTransfer.setData('text/plain',row.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>drag.current=null}><GripVertical size={16}/></span><span className={`file-icon ${scope.kind==='lessons'?'video':''}`}>{scope.kind==='lessons'?<FileVideo size={22}/>:<Folder size={22}/>}</span><button onClick={()=>scope.kind==='courses'?setScope({kind:'chapters',courseId:row.id}):scope.kind==='chapters'?setScope({kind:'lessons',courseId:course!.id,chapterId:row.id}):('status'in row&&row.status==='READY'?navigate(`/lessons/${row.id}`):undefined)}>{row.title}</button></span>
        <span className="file-info">{scope.kind==='courses'?<span className="vip-tag">VIP{(row as Course).requiredVip}</span>:scope.kind==='chapters'?`${(row as Chapter).lessons.length} 个小节`:<span className={`status-badge ${(row as Lesson).status==='READY'?'ready':''}`}>{(row as Lesson).status==='READY'?'可播放':'上传中'}</span>}</span><span className="file-actions"><button className="icon-button" aria-label={`编辑 ${row.title}`} onClick={()=>startEdit(row)}><Pencil size={15}/></button>{scope.kind!=='courses'&&<button className="icon-button" aria-label={`移动 ${row.title}`} onClick={()=>{setActionError('');setMove({kind:scope.kind as 'chapters'|'lessons',id:row.id,title:row.title});}}><MoveRight size={16}/></button>}<button className="icon-button delete" aria-label={`删除 ${row.title}`} onClick={()=>deletion(row)}><Trash2 size={15}/></button></span></div>)}</div>
      <UploadPanel chapterId={scope.kind==='lessons'?scope.chapterId:null} droppedFiles={files} onComplete={load}/>
    </div></div>}
    {edit&&<Modal title={`${edit.id?'编辑':'新建'}${edit.kind==='courses'?'课程':edit.kind==='chapters'?'章节':'小节'}`} onClose={()=>{if(!busy)setEdit(null);}}><form onSubmit={save}><label>名称<input name="title" defaultValue={edit.title} required maxLength={200}/></label>{edit.kind==='courses'&&<><label>课程简介<textarea name="description" defaultValue={edit.description} maxLength={5000} rows={4}/></label><label>最低 VIP 等级<select name="requiredVip" defaultValue={edit.requiredVip}>{[1,2,3,4,5].map(level=><option key={level} value={level}>VIP{level}</option>)}</select></label><label className="cover-field"><ImagePlus size={17}/>课程封面 <span className="small muted">JPEG / PNG / WebP，≤5MiB</span><input name="cover" type="file" accept="image/jpeg,image/png,image/webp"/></label><p className="small muted">保存后课程立即展示。上传中的视频不会对学员显示。</p></>}<ErrorNote message={actionError}/><div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>取消</button><button className="button" disabled={busy}>{busy?'保存中…':'保存'}</button></div></form></Modal>}
    {remove&&<Confirm title={`删除「${remove.title}」？`} message={remove.message} onClose={()=>setRemove(null)} onConfirm={deleteRow} busy={busy} error={actionError}/>}
    {move&&<Modal title={`移动「${move.title}」`} onClose={()=>{if(!busy)setMove(null);}}><form onSubmit={doMove}><p className="muted">移动后将继承目标课程的 VIP 权限，原学员可能失去访问，新学员可能获得访问。</p><label>目标{move.kind==='chapters'?'课程':'章节'}<select name="target" required>{targetOptions.map(option=><option value={option.id} key={option.id}>{option.title}</option>)}</select></label>{!targetOptions.length&&<p className="muted">尚无可用目标，请先创建另一个课程或章节。</p>}<ErrorNote message={actionError}/><div className="form-actions"><button className="button secondary" type="button" disabled={busy} onClick={()=>setMove(null)}>取消</button><button className="button" disabled={busy||!targetOptions.length}>{busy?'移动中…':'确认移动'}</button></div></form></Modal>}
  </>;
}
function UserManager(){
  const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<{users:Account[];total:number;pageSize:number}|null>(null),[error,setError]=useState(''),[edit,setEdit]=useState<Account|null>(null),[remove,setRemove]=useState<Account|null>(null),[password,setPassword]=useState<Account|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[vip,setVip]=useState(''),[version,setVersion]=useState(0);
  useEffect(()=>{let current=true;setData(null);api<{users:Account[];total:number;pageSize:number}>(`/admin/users?search=${encodeURIComponent(query)}&page=${page}`).then(r=>{if(current){setData(r);setError('');}}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[query,page,version]);
  const load=()=>setVersion(v=>v+1);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setActionError('');const form=Object.fromEntries(new FormData(e.currentTarget));try{if(password)await api(`/admin/users/${password.id}/password`,'POST',form);else if(edit)await api(`/admin/users/${edit.id}`,'PATCH',{...form,vipLevel:form.vipLevel?Number(form.vipLevel):null});setEdit(null);setPassword(null);load();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  async function deleteUser(){if(!remove)return;setBusy(true);try{await api(`/admin/users/${remove.id}`,'DELETE');setRemove(null);if(data?.users.length===1&&page>1)setPage(page-1);else load();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
  return <><div className="admin-page-heading"><div><span className="eyebrow">MEMBER ACCESS</span><h1>用户管理</h1><p>管理学员等级与有效期，权限将在下次请求时生效。</p></div><span className="count-pill">{data?.total||0} 位用户</span></div><form className="user-search" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);}}><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索手机号、邮箱或姓名" aria-label="搜索用户" maxLength={200}/><button className="button compact">搜索</button></form>
    {error?<ErrorState message={error} retry={load}/>:!data?<Loading/>:!data.users.length?<Empty title="没有找到用户"/>:<><div className="user-table"><div className="user-row user-table-head"><span>学员账号</span><span>VIP 等级</span><span>有效期</span><span>操作</span></div>{data.users.map(user=><div className="user-row" key={user.id}><div className="user-identity"><span className="avatar">{(user.name||user.email||user.phone||'U').slice(0,1).toUpperCase()}</span><div><strong>{user.name||user.email||user.phone}</strong><small>{user.name?(user.email||user.phone):user.phone&&user.email?user.phone:'已注册账号'}{user.role==='ADMIN'?' · 管理员':''}</small></div></div><span className={`vip-tag ${!user.vipLevel?'unset':''}`}>{vipLabel(user)}</span><span className={`user-expiry ${isExpired(user)?'expired':''}`}>{!user.vipLevel?'—':isExpired(user)?'已到期':user.vipExpiresAt?expiryInput(user.vipExpiresAt):'永久'}{user.vipExpiresAt&&<small>{dateLabel(user.vipExpiresAt)}</small>}</span><span className="user-actions"><button onClick={()=>{setActionError('');setEdit(user);setVip(user.vipLevel?String(user.vipLevel):'');}}>编辑</button><button onClick={()=>{setActionError('');setPassword(user);}}>重置密码</button>{user.role!=='ADMIN'&&<button className="delete" onClick={()=>{setActionError('');setRemove(user);}}>删除</button>}</span></div>)}</div><div className="pagination"><span>共 {data.total} 位用户 · 第 {page} 页</span><button className="button secondary compact" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><button className="button secondary compact" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(page+1)}>下一页</button></div></>}
    {edit&&<Modal title="编辑用户权限" onClose={()=>{if(!busy)setEdit(null);}}><form onSubmit={submit}><label>显示名称<input name="name" defaultValue={edit.name} maxLength={100}/></label><label>邮箱<input name="email" defaultValue={edit.email||''} type="email" maxLength={254}/></label><label>手机号<input name="phone" defaultValue={edit.phone||''} type="tel" maxLength={30}/></label><label>VIP 等级<select name="vipLevel" value={vip} onChange={e=>setVip(e.target.value)}><option value="">未设置</option>{[1,2,3,4,5].map(v=><option value={v} key={v}>VIP{v}</option>)}</select></label><label>有效至（北京时间）<input name="expiresDate" type="date" defaultValue={expiryInput(edit.vipExpiresAt)} disabled={!vip}/><span className="small muted">留空为永久；指定日期当天结束后失效。</span></label><ErrorNote message={actionError}/><div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>取消</button><button className="button" disabled={busy}>{busy?'保存中…':'保存权限'}</button></div></form></Modal>}
    {password&&<Modal title="重置密码" onClose={()=>{if(!busy)setPassword(null);}}><form onSubmit={submit}><p className="muted">重置 {password.email||password.phone} 的密码。该账号所有已有登录会话将立即失效。</p><label>新密码<input name="password" type="password" required minLength={6} maxLength={128} autoComplete="new-password"/></label><ErrorNote message={actionError}/><div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setPassword(null)}>取消</button><button className="button" disabled={busy}>{busy?'处理中…':'确认重置'}</button></div></form></Modal>}
    {remove&&<Confirm title="删除用户？" message={`将永久删除 ${remove.email||remove.phone}，其登录会话与课程权限将立即失效。`} onClose={()=>setRemove(null)} onConfirm={deleteUser} busy={busy} error={actionError}/>}
  </>;
}
