import { ArrowRight, ArrowUpRight, Check, Code2, Workflow, Bot, Database, AudioLines, Target, Sparkles, Play, Command, Layers, Mail, ChevronRight } from 'lucide-react';
import { homeContent as content, commercialGuarantee } from '../src/content/home';
import { useAuth } from './auth';
import { Link } from 'react-router-dom';
const icons=[Bot,Code2,Workflow,Database,AudioLines,Target];
export default function Home(){
  const {user,openLogin}=useAuth();
  return <main className="home">
    <section className="hero section-wrap"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> LEARN. BUILD. DELIVER.</span><h1>把 AI 技术，<br/>变成客户愿意<br/><span className="gradient-text">付费的服务。</span></h1><p className="hero-description">从第一个 AI Agent，到你的第一个客户。<br/>用清晰的路线图，把工具能力变成真实的商业价值。</p><div className="hero-buttons"><a className="button large" href="#products">了解 VIP 路线<ArrowUpRight size={19}/></a><a className="text-button" href="#curriculum"><span className="play-small"><Play size={13} fill="currentColor"/></span>探索课程体系</a></div><div className="hero-note"><ShieldIcon/>技术实战 · 项目指导 · 商业陪跑<span>选择适合你的起点</span></div></div>
    <div className="hero-art" aria-label="从AI项目到客户服务的实践路线"><div className="art-orbit"/><div className="floating-tag tag-code"><Command size={17}/> Claude Code<span className="tag-dot"/></div><div className="floating-tag tag-workflow"><Workflow size={17}/> n8n Automation</div><div className="project-window"><div className="window-bar"><span className="window-dots"><i/><i/><i/></span><span>your-first-ai-service</span><Code2 size={13}/></div><div className="window-content"><div className="project-badge"><Sparkles size={15}/> AI SERVICE BUILDER</div><h3>从想法，到落地。<span>你的第一个 AI 服务</span></h3><div className="workflow-line"><div><span className="node lavender"><Mail size={20}/></span><small>客户需求</small></div><i/><div><span className="node purple"><Bot size={23}/></span><small>AI Agent</small></div><i/><div><span className="node mint"><Check size={23}/></span><small>解决方案</small></div></div><div className="mock-code"><span><b>01</b><em>const</em> service = <em>await</em> build(&#123;</span><span><b>02</b>  problem: <strong>"a real business need"</strong>,</span><span><b>03</b>  solution: <strong>"powered by AI"</strong></span><span><b>04</b>&#125;);</span></div><div className="window-footer"><span className="status-dot"/> Demo ready to present <span>↗</span></div></div></div><div className="floating-card"><span className="success-icon"><Check size={20}/></span><div><strong>让技术创造价值</strong><small>Demo → Offer → Client</small></div><Sparkles size={19}/></div><div className="art-label">YOUR NEXT CHAPTER STARTS HERE</div></div></section>
    <section className="tools-strip"><p>从这些工具出发，构建真正可交付的服务</p><div><span><Command/>Claude Code</span><span><Workflow/>n8n</span><span><Code2/>Vibe Coding</span><span><Bot/>AI Agent</span><span><Database/>RAG</span><span><AudioLines/>Voice Agent</span></div></section>
    <section className="section-wrap challenge-section"><div><span className="eyebrow">YOUR STARTING POINT</span><h2>会用 AI 工具，<br/>下一步怎么走？</h2><p className="section-description">把零散的学习，连接到一个具体的目标。<br/>你需要的不只是更多教程，还有行动的方向。</p></div><div className="challenge-list">{content.challenges.items.map((item,i)=><div key={item}><span>0{i+1}</span><p>{item}</p><ChevronRight size={17}/></div>)}</div></section>
    <section className="curriculum-section" id="curriculum"><div className="section-wrap"><div className="section-heading"><span className="eyebrow">BUILD YOUR CAPABILITIES</span><h2>一套连接技术与商业的课程体系</h2><p>{content.hero.description}</p></div><div className="curriculum-grid">{content.curriculum.items.map((item,i)=>{const Icon=icons[i];return <article key={item.title} className="capability"><div className={`capability-icon color-${i}`}><Icon size={25}/></div><span className="capability-index">0{i+1}</span><h3>{item.title}</h3><p>{item.description}</p><span className="capability-bottom">从方法到实践<ArrowUpRight size={17}/></span></article>;})}</div><p className="curriculum-note">{content.curriculum.note}</p></div></section>
    <section className="section-wrap roadmap-section"><div className="section-heading"><span className="eyebrow">A CLEAR PATH FORWARD</span><h2>{content.goal.title}</h2><p>每一阶段都有明确的产出，让你的能力一步步接近真实客户。</p></div><div className="roadmap">{content.goal.stages.map((stage,i)=><article key={stage.title}><span className="roadmap-number">0{i+1}</span><small>{['BUILD','PACKAGE','CONNECT','DELIVER'][i]}</small><h3>{stage.title}</h3><p>{stage.description}</p></article>)}</div></section>
    <section id="advantages" className="advantages-section"><div className="section-wrap advantages-inner"><div><span className="eyebrow">LESS GUESSWORK. MORE PROGRESS.</span><h2>你的学习，<br/>应该带你走得更远。</h2><p className="section-description">未来不缺会用 AI 的人。<br/>真正有价值的是，能用 AI 帮客户解决问题的人。</p></div><div className="advantages-list">{content.advantages.map((item,i)=><article key={item.title}><span><Layers size={22}/></span><div><small>0{i+1}</small><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></div></section>
    <section className="section-wrap products-section" id="products"><div className="section-heading"><span className="eyebrow">FIND YOUR FIT</span><h2>选择适合你当前阶段的 VIP 路线</h2><p>从入门到商业执行，按你需要的内容与支持深度选择。</p></div><div className="pricing-grid">{content.products.map((product,i)=><article className={`pricing-card ${i===2?'featured':''}`} key={product.id}>{i===2&&<span className="featured-label">从学习走向实战</span>}<span className="plan-tier">{product.id} / {['START','LEARN','BUILD','GROW'][i]}</span><h3>{product.title}</h3><p className="plan-audience">{product.audience}</p><div className="plan-price">{product.price}<span>{'period'in product?` / ${product.period}`:''}</span></div><p className="annual-price">{'annualPrice'in product?`${product.annualPrice} · 12个月权益`:'一次选择，明确交付'}</p><a href="#join" className={`button ${i===2?'':'secondary'} full`}>了解这一档<ArrowRight size={16}/></a><div className="plan-features">{product.features.map(feature=><p key={feature}><Check size={16}/>{feature}</p>)}</div>{'guarantee'in product&&<p className="guarantee-note">{product.guarantee}</p>}<p className="plan-boundary">{product.boundary}</p></article>)}</div><p className="pricing-note">网站仅用于课程学习与权限管理。报名、人工指导及陪跑服务在线下完成。</p></section>
    <section className="section-wrap outcomes-section" id="outcomes"><div><span className="eyebrow">MAKE YOUR WORK VISIBLE</span><h2>让你的努力，<br/>成为看得见的成果。</h2><p className="section-description">完成项目只是开始。<br/>把它整理成客户能理解的价值。</p></div><div className="outcome-board"><div className="board-top"><span><Target size={18}/> 实践成果清单</span><small>YOUR PORTFOLIO</small></div>{content.outcomes.items.map((item,i)=><div className="outcome-row" key={item}><span className="outline-check"><Check size={13}/></span>{item}<small>0{i+1}</small></div>)}<p>以上为学习目标，真实学员案例将经核实和授权后展示。</p></div></section>
    <section className="section-wrap fit-section"><span className="eyebrow">FOR PEOPLE WHO TAKE ACTION</span><h2>{content.fit.title}</h2><div><p>{content.fit.suitable}</p><p>{content.fit.unsuitable}</p></div></section>
    <section className="section-wrap faq-section"><div><span className="eyebrow">GOOD QUESTIONS</span><h2>你可能想了解</h2><p className="muted">选择之前，把服务内容与边界看清楚。</p></div><div className="faq-list">{content.faq.map(item=><details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <section className="section-wrap" id="join"><div className="join-section"><span className="eyebrow">TURN KNOWLEDGE INTO SOMETHING REAL</span><h2>你的第一个 AI 服务，<br/>从这里开始。</h2><p>选定一个问题，做出一个 Demo，开始一次真实的客户沟通。</p>{user?<Link className="button white large" to="/my-courses">进入我的课堂<ArrowUpRight size={18}/></Link>:<button className="button white large" onClick={openLogin}>注册学习账号<ArrowUpRight size={18}/></button>}<div className="join-guarantee"><Check size={16}/>{commercialGuarantee.copy}</div><small>报名请联系课程负责人；注册不会自动产生订单或课程权限。</small></div></section>
    <footer className="footer section-wrap"><div><strong>AI FDE <span>ACADEMY</span></strong><p>把 AI 技术做成可成交的服务。</p></div><span>© {new Date().getFullYear()} AI FDE Academy</span><a href="#curriculum">开始探索<ArrowUpRight size={15}/></a></footer>
  </main>;
}
function ShieldIcon(){return <span className="tiny-shield"><Check size={12}/></span>;}
