import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, ChevronRight, LockKeyhole, Play, Sparkles } from 'lucide-react';
import { api, type Course, isExpired, vipLabel } from './api';
import { useAuth } from './auth';
import { Empty, ErrorState, Loading, Modal } from './ui';
function useLoad<T>(path:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0);useEffect(()=>{let current=true;setData(null);setError('');api<T>(path).then(r=>{if(current)setData(r);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[path,version]);return {data,error,retry:()=>setVersion(v=>v+1)};}
export function CourseList({mine=false}:{mine?:boolean}){
  const {user}=useAuth();const {data,error,retry}=useLoad<{courses:Course[]}>(`/courses${mine?'?mine=1':''}`);const [locked,setLocked]=useState<Course|null>(null);
  return <main className="page"><div className="page-heading"><div><span className="eyebrow">{mine?'YOUR LEARNING SPACE':'EXPLORE THE LIBRARY'}</span><h1>{mine?'我的课程':'全部课程'}</h1><p>{mine?'从一个小节开始，让学习变成行动。':'探索课程体系，找到你的下一步。'}</p></div><span className="vip-pill"><Sparkles size={16}/>{vipLabel(user!)}{isExpired(user!)?' · 已到期':''}</span></div>
    {error?<ErrorState message={error} retry={retry}/>:!data?<Loading/>:!data.courses.length?<Empty title={mine?(isExpired(user!)?'课程权限已到期':'还没有可以学习的课程'):'课程正在准备中'}><p className="muted">{mine?'请联系管理员开通或续期对应的 VIP 权限。':'课程上线后会显示在这里。'}</p>{mine&&<Link className="button secondary" to="/courses">浏览全部课程<ArrowRight size={16}/></Link>}</Empty>:<div className="course-grid">{data.courses.map((course,i)=><article className="course-card" key={course.id}><div className={`course-cover cover-${i%4}`}>{course.coverUrl?<img src={course.coverUrl} alt={course.title} loading="lazy"/>:<><div className="cover-shape"/><BookOpen size={46}/><span>AI FDE / CLASSROOM</span></>}<span className="cover-vip">VIP{course.requiredVip}</span>{!course.accessible&&<div className="cover-lock"><LockKeyhole size={24}/></div>}</div><div className="course-body"><span className="course-kicker">{course.accessible?'可开始学习':'VIP 专属课程'}</span><h2>{course.title}</h2><p>{course.description||'从基础到实践，构建你的 AI 能力。'}</p>{course.accessible?<Link className="course-action" to={`/courses/${course.id}`}>进入课程<ArrowUpRightSmall/></Link>:<button className="course-action locked" onClick={()=>setLocked(course)}><span><LockKeyhole size={14}/>需要 VIP{course.requiredVip}</span><ChevronRight size={17}/></button>}</div></article>)}</div>}
    {locked&&<Modal title="这门课程需要更高的权限" onClose={()=>setLocked(null)}><div className="lock-dialog-icon"><LockKeyhole size={30}/></div><h3>{locked.title}</h3><p className="muted">你的当前等级：{vipLabel(user!)}{isExpired(user!)?'（已到期）':''}<br/>该课程需要：VIP{locked.requiredVip}，且权限未到期。</p><p className="small muted">请联系管理员调整等级或有效期。</p><button className="button full" onClick={()=>setLocked(null)}>知道了</button></Modal>}
  </main>;
}
function ArrowUpRightSmall(){return <ArrowRight size={17}/>;}
export function CourseDetail(){
  const {id}=useParams();const {data,error,retry}=useLoad<{course:Course}>(`/courses/${id}`);if(error)return <main className="page"><Link className="back-link" to="/my-courses"><ArrowLeft size={16}/>返回课程列表</Link><ErrorState message={error} retry={retry}/></main>;if(!data)return <Loading/>;
  const course=data.course,total=course.chapters?.reduce((n,ch)=>n+ch.lessons.length,0)||0;
  return <main className="page course-detail"><Link className="back-link" to="/my-courses"><ArrowLeft size={16}/>返回我的课程</Link><section className="course-intro"><div><span className="vip-pill">VIP{course.requiredVip} 专属课程</span><h1>{course.title}</h1><p>{course.description||'欢迎开始你的课程实践。'}</p><div className="course-meta"><BookOpen size={16}/>{course.chapters?.length||0} 个章节<span>·</span><Play size={15}/>{total} 个视频小节</div></div>{course.coverUrl&&<img className="intro-cover" src={course.coverUrl} alt="课程封面"/>}</section><div className="outline-heading"><h2>课程目录</h2><span>{total} 个小节</span></div>{!total?<Empty title="课程内容准备中"><p className="muted">课程视频上传完成后会显示在这里。</p></Empty>:course.chapters?.map((chapter,i)=><section className="chapter-card" key={chapter.id}><h3><span>{String(i+1).padStart(2,'0')}</span>{chapter.title}<small>{chapter.lessons.length} 小节</small></h3>{!chapter.lessons.length?<p className="chapter-empty">本章内容准备中</p>:chapter.lessons.map((lesson,j)=><Link key={lesson.id} className="lesson-link" to={`/lessons/${lesson.id}`}><span className="lesson-play"><Play size={13}/></span><span>{lesson.title}</span><small>{i+1}.{j+1}</small><ChevronRight size={16}/></Link>)}</section>)}</main>;
}
export function Player(){
  const {id}=useParams();const {data,error,retry}=useLoad<{lesson:{id:string;title:string;courseId:string;courseTitle:string;videoUrl:string;nextId:string|null}}>(`/lessons/${id}`);const video=useRef<HTMLVideoElement>(null);const [mediaError,setMediaError]=useState('');useEffect(()=>setMediaError(''),[id]);
  if(error)return <main className="page"><ErrorState message={error} retry={retry}/></main>;if(!data)return <Loading/>;const lesson=data.lesson;
  return <main className="page player-page"><Link className="back-link" to={`/courses/${lesson.courseId}`}><ArrowLeft size={16}/>返回课程</Link><p className="eyebrow">{lesson.courseTitle}</p><h1>{lesson.title}</h1><div className="video-shell"><video key={lesson.id} ref={video} controls playsInline preload="metadata" src={lesson.videoUrl} onError={async()=>{try{const r=await fetch(lesson.videoUrl,{method:'HEAD'});setMediaError(r.status===401?'登录已失效，请重新登录。':r.status===403?'课程权限不足或已到期，请联系管理员。':'视频暂时无法播放，请重新加载或联系管理员。');}catch{setMediaError('网络连接失败，请稍后重试。');}}}/></div>{mediaError&&<ErrorState message={mediaError} retry={()=>{setMediaError('');video.current?.load();}}/>}<div className="player-controls"><label>播放速度<select defaultValue="1" key={id} onChange={e=>{if(video.current)video.current.playbackRate=Number(e.target.value);}}>{[0.75,1,1.25,1.5,1.75,2].map(speed=><option key={speed} value={speed}>{speed}×</option>)}</select></label>{lesson.nextId?<Link className="button" to={`/lessons/${lesson.nextId}`}>下一节<ArrowRight size={17}/></Link>:<Link className="button secondary" to={`/courses/${lesson.courseId}`}>返回课程<ArrowRight size={17}/></Link>}</div></main>;
}
